Repository gdsc-ssu/keyword-z, pull requests merged in 2023-12, with the labels that each got.

#3 chore: 프로젝트 초기 세팅
  index.html
  package.json
  public/cat-favicon.png
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/logo/Logo-Vector.png
  src/assets/react.svg
  src/components/moblieFrame.tsx
  src/data/index.tsx
  src/index.css
  src/pages/index.tsx
  src/pages/mainHome/Home.tsx
  src/styles/index.tsx
  yarn.lock
Labels: chore, design

#4 Chore/#2
  package.json
  src/App.tsx
  src/assets/QuizImage/Q1.jpg
  src/assets/QuizImage/Q10.jpg
  src/assets/QuizImage/Q2.png
  src/assets/QuizImage/Q3.png
  src/assets/QuizImage/Q4.jpg
  src/assets/QuizImage/Q5.jpg
  src/assets/QuizImage/Q6.png
  src/assets/QuizImage/Q7.png
  src/assets/QuizImage/Q8.jpg
  src/assets/QuizImage/Q9.jpg
  src/data/questions.ts
  src/pages/quiz/Quiz.tsx
  yarn.lock
Labels: chore, feat, design

#5 Feat: 홈 화면 작업
  package.json
  public/cat-favicon2.png
  src/assets/Anim/cat.json
  src/components/moblieFrame.tsx
  src/data/index.tsx
  src/data/questions.ts
  src/pages/Home/Home.tsx
  src/pages/Home/HomeWrap.tsx
  src/pages/index.tsx
  src/pages/mainHome/Home.tsx
  yarn.lock
Labels: feat, design

#6 Chore: 이동로직 수정
  src/App.tsx
  src/data/questions.ts
  src/pages/Home/Home.tsx
  src/pages/Home/HomeWrap.tsx
  src/pages/quiz/Quiz.tsx
Labels: chore, feat

#8 chore: 파이어베이스 추가
  index.html
  src/data/questions.ts
Labels: chore

#9 Fix/quiz bug fix
  src/data/questions.ts
  src/pages/quiz/Quiz.tsx
Labels: feat
